# Generated by Django 5.1.4 on 2024-12-05 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Texto de la Pregunta')),
                ('type', models.CharField(choices=[('text', 'Texto Libre'), ('number', 'Número'), ('dropdown', 'Opciones Desplegables')], max_length=20, verbose_name='Tipo de Respuesta')),
                ('options', models.TextField(blank=True, null=True, verbose_name='Opciones (separadas por comas)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de la Pregunta')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.category', verbose_name='Categoría')),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
    ]
