# Generated by Django 5.1.4 on 2024-12-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('EVALUATOR', 'Evaluador'), ('CLIENT', 'Emprendedor')], default='CLIENT', max_length=20, verbose_name='Perfil'),
        ),
    ]
