# Generated by Django 5.1.4 on 2024-12-05 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de la Idea')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de evaluación'), ('rejected', 'Rechazada'), ('approved', 'Aprobada'), ('incomplete', 'Sin terminar')], default='incomplete', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Idea',
                'verbose_name_plural': 'Ideas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Respuesta')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ideas.idea', verbose_name='Idea')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de Idea',
                'verbose_name_plural': 'Respuestas de Ideas',
                'unique_together': {('idea', 'question')},
            },
        ),
    ]
