# Generated by Django 5.1.4 on 2024-12-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
    ]
