# Generated by Django 5.1.4 on 2024-12-16 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_idea_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(7.0)], verbose_name='Nota'),
        ),
    ]
